<h2> Liora Wachsstock <h2/>
<h3> Python For Data Science Project 1 <h3/>

In [1]:
#import statements
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
def print_data(X_train, X_test, y_train, y_test, result, seed):
    print("The seed was", seed)
    
    print("Training Data:")
    for i, point in enumerate(X_train):
        print(point, "    ", y_train[i])
    
    print("\nTest Data:")
    for i, point in enumerate(X_test):
        print(point, "    ", y_test[i])
    
    
    print("\nPredicted labels:")
    for i, point in enumerate(X_test):
        print(point, "    ", result[i])
    
    print("Accuracy: ", round((np.sum(result == y_test)/len(result))*100,2), "%")

In [3]:
def generate_data(seed_num, TOTAL_SAMPLE_SIZE,n,d,m,s):
    label_names = ["good", "bad", "ugly"]
    
    #Seed
    rng = np.random.default_rng(seed = seed_num)
    
    #Generate Data set and labels
    total_sample_set = rng.normal(m, s, d*TOTAL_SAMPLE_SIZE).reshape(TOTAL_SAMPLE_SIZE, d)
    labels = rng.choice(label_names, TOTAL_SAMPLE_SIZE)
    
    #Get the indicies for separating test and training data
    training_ind = np.random.choice(np.arange(TOTAL_SAMPLE_SIZE), n, replace=False) #get random indicies for training data
    test_ind = np.setdiff1d(np.arange(TOTAL_SAMPLE_SIZE), training_ind) #get the indicies not chosen
    
    #Separate the data
    X_train = total_sample_set[training_ind]
    y_train = labels[training_ind]
    
    X_test = total_sample_set[test_ind]
    y_test = labels[test_ind]
    
    return X_train, X_test, y_train, y_test

In [4]:
def weigh(distance):
    return 1/(distance + 0.0001)

def distances(train, point):
    return np.linalg.norm((train - point), axis=1)

def vote(distances, kclasses, k):
    labels = ["good", "bad", "ugly"]
    
    votes = np.zeros(len(labels), dtype=np.float32)
    
    weight = np.vectorize(weigh)
    
    w = weight(distances)
    
    votes = [np.sum(w[kclasses == labels[0]]), np.sum(w[kclasses == labels[1]]), np.sum(w[kclasses == labels[2]])]
    return labels[np.argmax(votes)] #get the winner

def kneighbors(X_train, y_train, X_test, k):
    classes = []
    for point in X_test:
        dists = distances(X_train, point)      #1.Find its Euclidean distance from each of the n points in the training data set 
        smallestK = np.argsort(dists)[:k]    #2.Pick the nearest K points (returns the indicies)
        classes.append(vote(dists[smallestK], y_train[smallestK], k)) #3.Output the class by weighted voting using the K nearest neighbors in the above step 

    return classes

In [5]:
TOTAL_SAMPLE_SIZE = 10 # Total number of samples (data points or vectors) in the training set plus test set
n = 7 #Number of samples (data points or vectors) in the training set
d = 3 #Number of features
K = 3 #Stipulated number of nearest neighbors
m = 5 #mean of normal distribution
s = 2 #std of normal distrubution

In [6]:
print("Run #1")
seed = 42
X_train, X_test, y_train, y_test = generate_data(seed, TOTAL_SAMPLE_SIZE, n, d, m, s)

result = kneighbors(X_train, y_train, X_test, K)
print_data(X_train, X_test, y_train, y_test, result, seed)


Run #1
The seed was 42
Training Data:
[3.63814091 7.44508268 4.69094104]      bad
[3.28141507 5.73750157 3.0822348 ]      good
[6.88112943 1.09792962 2.39564099]      ugly
[5.60943416 2.92003179 6.50090239]      ugly
[6.7569006  4.90014818 4.63027527]      ugly
[5.25568081 4.36751482 4.96639768]      bad
[5.1320614  7.25448241 5.93501868]      bad

Test Data:
[3.29391214 6.75879595 6.55558387]      ugly
[4.14334436 4.2957329  6.06461837]      good
[5.73088813 5.82546522 5.86164201]      bad

Predicted labels:
[3.29391214 6.75879595 6.55558387]      bad
[4.14334436 4.2957329  6.06461837]      ugly
[5.73088813 5.82546522 5.86164201]      bad
Accuracy:  33.33 %


In [7]:
print("Run #2")
seed = 15
X_train, X_test, y_train, y_test = generate_data(seed, TOTAL_SAMPLE_SIZE, n, d, m, s)

result = kneighbors(X_train, y_train, X_test, K)

print_data(X_train, X_test, y_train, y_test, result, seed)

Run #2
The seed was 15
Training Data:
[1.8789206  5.40957495 6.38195717]      good
[7.88661118 3.77339661 5.1555479 ]      ugly
[3.3740433  4.15533326 0.4411023 ]      good
[2.13825395 3.12690457 5.78787671]      ugly
[7.78652099 6.06568803 8.32127508]      good
[2.11293722 7.03412758 3.8087027 ]      bad
[9.18816997 6.45737788 3.92202114]      good

Test Data:
[3.95182674 6.05123241 6.61464725]      bad
[5.40297558 5.42995584 5.65903622]      good
[6.26844023 4.64451783 1.95118423]      good

Predicted labels:
[3.95182674 6.05123241 6.61464725]      good
[5.40297558 5.42995584 5.65903622]      good
[6.26844023 4.64451783 1.95118423]      good
Accuracy:  66.67 %
